[server]
ip = "0.0.0.0"
document_root = "public"

[https]
port = 8443
# redirect = ""
threads = 4

[https.ssl]
identity = ""
password = ""

[http]
port = 8080
redirect = "https://localhost:8443"
threads = 4

